### PR TITLE
Use fix version of vulnerable dependent package

### PR DESCRIPTION
**Pull request by baurzhan-konurbayev**
There was a security vulnerability published for ejs package https://snyk.io/vuln/SNYK-JS-EJS-1049328
Bumping dependent package version to use its fix version

### CODE REVIEW

**Comment by katliger-h** [comment]
@baurzhan-konurbayev Thanks for fixing this, hope this can be merged soon!

**Comment by aperyk-nix** [comment]
@baurzhan-konurbayev, @surma would be nice to have new version with vulnerable fix.

**Comment by KhemSachdevaFluke** [comment]
@surma Can you pls help here as we are waiting for this fix.

**Comment by tomasz-zylka-fluke** [comment]
@surma @baurzhan-konurbayev yep our team is also looking forward to that fix...

**Comment by surma** [comment]
Thanks for your patience, everyone!

**Comment by aperyk-nix** [comment]
@surma Thanks for merge it, could you please share when it will go to release ? v1 is also required to have this fix.

**Comment by surma** [comment]
I won’t be updating v1. It’s not an actively maintained version of this plugin.

Keep in mind that this is *not* an actual security vulnerability. ejs is only used during build time to create the AMD loader code.

**Pull request merged**
